import sys
sys.stdout.reconfigure(encoding='utf-8')

with open('习思想期末复习/刷题题库.html', 'r', encoding='utf-8') as f:
    content = f.read()

start = content.find('const questions=[')
end = content.find('];', start) + 2

new_questions = """const questions=[
{id:1,chapter:0,type:'single',question:'"两个结合"是我们取得成功的（    ）。',options:['重要法宝','最大法宝','根本保证','关键所在'],answer:[1],explanation:'"两个结合"是我们取得成功的最大法宝。P4'},
{id:2,chapter:0,type:'single',question:'党的十九大把习近平新时代中国特色社会主义思想确立为党必须长期坚持的指导思想并写入党章，时间是（    ）。',options:['2016年10月','2017年10月','2018年3月','2021年11月'],answer:[1],explanation:'2017年10月，党的十九大确立为指导思想并写入党章。P9'},
{id:3,chapter:0,type:'single',question:'"十个明确"是习近平新时代中国特色社会主义思想的（    ）。',options:['基本方略','主体内容','世界观和方法论','实践总结'],answer:[1],explanation:'"十个明确"是主体内容，构成四梁八柱，发挥统摄作用。P7'},
{id:4,chapter:0,type:'single',question:'"十四个坚持"构成了新时代坚持和发展中国特色社会主义事业的（    ）。',options:['根本保证','指导思想','基本方略','行动指南'],answer:[2],explanation:'"十四个坚持"构成了基本方略。P7'},
{id:5,chapter:0,type:'single',question:'"两个确立"是党在新时代取得的（    ）。',options:['重要经验','理论创新','实践成果','重大政治成果'],answer:[3],explanation:'"两个确立"是党在新时代取得的重大政治成果，对推进中华民族伟大复兴历史进程具有决定性意义。P10'},
{id:6,chapter:0,type:'multiple',question:'习近平新时代中国特色社会主义思想创立的时代背景包括（    ）。',options:['世界百年未有之大变局加速演进','中华民族伟大复兴进入关键时期','中国式现代化全面推进拓展','科学社会主义在21世纪的中国焕发新的蓬勃生机','中国共产党自我革命开辟新的境界'],answer:[0,1,2,3,4],explanation:'P1-3'},
{id:7,chapter:0,type:'multiple',question:'"六个必须坚持"包括（    ）。',options:['必须坚持人民至上','必须坚持自信自立','必须坚持守正创新','必须坚持问题导向','必须坚持系统观念','必须坚持胸怀天下'],answer:[0,1,2,3,4,5],explanation:'P8'},
{id:8,chapter:0,type:'multiple',question:'习近平新时代中国特色社会主义思想是（    ）。',options:['马克思主义基本原理同中国具体实际相结合的重大成果','马克思主义基本原理同中华优秀传统文化相结合的重大成果','当代中国马克思主义','二十一世纪马克思主义'],answer:[0,1,2,3],explanation:'P4, P9'},
{id:9,chapter:0,type:'multiple',question:'"两个确立"的意义在于（    ）。',options:['是党在新时代取得的重大政治成果','对新时代党和国家事业发展具有决定性意义','对推进中华民族伟大复兴历史进程具有决定性意义','是党和人民应对一切不确定性的最大确定性'],answer:[0,1,2,3],explanation:'P10-11'},
{id:10,chapter:0,type:'multiple',question:'习近平新时代中国特色社会主义思想回答的重大时代课题包括（    ）。',options:['坚持和发展什么样的中国特色社会主义','怎样坚持和发展中国特色社会主义','建设什么样的社会主义现代化强国','怎样建设社会主义现代化强国'],answer:[0,1,2,3],explanation:'P6'},
{id:11,chapter:0,type:'fill',question:'习近平新时代中国特色社会主义思想是"______"的重大成果。',answer:'两个结合',explanation:'P4'},
{id:12,chapter:0,type:'fill',question:'"十个明确"构成了这一思想体系的______，发挥着统摄作用。',answer:'四梁八柱',explanation:'P7'},
{id:13,chapter:0,type:'fill',question:'"十三个方面成就"对新时代伟大实践进行了______，全景展示了习近平新时代中国特色社会主义思想的理论与实践成果。',answer:'科学总结',explanation:'P8'},
{id:14,chapter:0,type:'fill',question:'习近平新时代中国特色社会主义思想是______文化和中国精神的时代精华。',answer:'中华',explanation:'P9'},
{id:15,chapter:0,type:'fill',question:'新时代新征程上必须深刻领悟"两个确立"的决定性意义，增强"______"、坚定"四个自信"、做到"两个维护"。',answer:'四个意识',explanation:'P11'},
{id:16,chapter:1,type:'single',question:'道路问题是关系党的事业兴衰成败（    ）的问题。',options:['最重要','第一位','最根本','最关键'],answer:[1],explanation:'P15'},
{id:17,chapter:1,type:'single',question:'中国特色社会主义是科学社会主义理论逻辑和中国社会发展历史逻辑的（    ）。',options:['有机统一','辩证统一','历史统一','逻辑统一'],answer:[1],explanation:'P18'},
{id:18,chapter:1,type:'single',question:'我们说要坚定道路自信、理论自信、制度自信，说到底是要坚定（    ）。',options:['道路自信','理论自信','制度自信','文化自信'],answer:[3],explanation:'P22'},
{id:19,chapter:1,type:'single',question:'全面建设社会主义现代化国家是（    ），在"四个全面"中居于引领地位。',options:['战术目标','基本方略','战略目标','根本保证'],answer:[2],explanation:'P31'},
{id:20,chapter:1,type:'single',question:'我国社会主要矛盾的变化，是我们党作出中国特色社会主义进入新时代重大判断的（    ）。',options:['根本依据','基本依据','重要前提','基本条件'],answer:[1],explanation:'P24'},
{id:21,chapter:1,type:'single',question:'党的基本理论是坚持和发展中国特色社会主义的（    ）。',options:['根本保证','重要基础','行动指南','基本遵循'],answer:[2],explanation:'P30'},
{id:22,chapter:1,type:'multiple',question:'改革开放以来我们取得一切成绩和进步的根本原因，归结起来就是（    ）。',options:['开辟了中国特色社会主义道路','形成了中国特色社会主义理论体系','确立了中国特色社会主义制度','发展了中国特色社会主义文化'],answer:[0,1,2,3],explanation:'P20'},
{id:23,chapter:1,type:'multiple',question:'道路、理论体系、制度、文化四者的关系是（    ）。',options:['道路是实现途径','理论体系是行动指南','制度是根本保障','文化是精神力量'],answer:[0,1,2,3],explanation:'P20'},
{id:24,chapter:1,type:'multiple',question:'中国特色社会主义进入新时代的三个"意味着"包括（    ）。',options:['意味着中华民族迎来了从站起来、富起来到强起来的伟大飞跃','意味着科学社会主义在21世纪的中国焕发出强大生机活力','意味着中国特色社会主义道路、理论、制度、文化不断发展','意味着我国社会主要矛盾发生了变化'],answer:[0,1,2],explanation:'P23'},
{id:25,chapter:1,type:'multiple',question:'新时代伟大变革在（    ）上具有里程碑意义。',options:['党史','新中国史','改革开放史','社会主义发展史','中华民族发展史'],answer:[0,1,2,3,4],explanation:'P28'},
{id:26,chapter:1,type:'multiple',question:'中国特色社会主义进入新时代的反映包括（    ）。',options:['我国社会主要矛盾发生新变化','党的主要任务发生新变化','中国和世界关系发生新变化','我国基本国情发生根本变化'],answer:[0,1,2],explanation:'P23-24'},
{id:27,chapter:1,type:'multiple',question:'新征程上，协调推进"四个全面"战略布局必须（    ）。',options:['紧紧扭住全面建设社会主义现代化国家这个战略目标不动摇','紧紧扭住全面深化改革不放松','紧紧扭住全面依法治国不放松','紧紧扭住全面从严治党不放松'],answer:[0,1,2,3],explanation:'P31-32'},
{id:28,chapter:1,type:'fill',question:'中国特色社会主义进入新时代，是我国发展新的______。',answer:'历史方位',explanation:'P14'},
{id:29,chapter:1,type:'fill',question:'中国特色社会主义是______和人民的选择。',answer:'历史',explanation:'P15'},
{id:30,chapter:1,type:'fill',question:'我们既要看到我国社会主要矛盾发生的变化，也要看到我国仍处于并将长期处于社会主义______的基本国情没有变。',answer:'初级阶段',explanation:'P26'},
{id:31,chapter:1,type:'fill',question:'中国特色社会主义写出了科学社会主义的"______"。',answer:'新版本',explanation:'P19'},
{id:32,chapter:1,type:'fill',question:'"五位一体"总体布局和协调推进"______"战略布局。',answer:'四个全面',explanation:'P29-32'},
{id:33,chapter:1,type:'fill',question:'全面深化改革、全面依法治国、全面从严治党是三大______，为全面建设社会主义现代化国家提供重要保障。',answer:'战略举措',explanation:'P31'},
{id:34,chapter:2,type:'single',question:'新时代新征程中国共产党的中心任务，就是以（    ）全面推进中华民族伟大复兴。',options:['改革开放','中国式现代化','高质量发展','共同富裕'],answer:[1],explanation:'P35'},
{id:35,chapter:2,type:'single',question:'中国式现代化是强国建设、民族复兴的（    ）。',options:['重要途径','唯一正确道路','必然选择','根本保证'],answer:[1],explanation:'P41'},
{id:36,chapter:2,type:'single',question:'实现中华民族伟大复兴的中国梦，本质是（    ）。',options:['经济发展、政治民主、文化繁荣','国家统一、民族团结、社会稳定','国家富强、民族振兴、人民幸福','科技进步、教育发展、民生改善'],answer:[2],explanation:'P37'},
{id:37,chapter:2,type:'single',question:'团结奋斗是中国共产党和中国人民最显著的（    ）。',options:['优良传统','精神标识','政治优势','制度优势'],answer:[1],explanation:'P53'},
{id:38,chapter:2,type:'single',question:'全面建成小康社会是实现中华民族伟大复兴中国梦的（    ）。',options:['根本保证','重要基础','关键一步','必然要求'],answer:[2],explanation:'P35'},
{id:39,chapter:2,type:'single',question:'中国式现代化是中国共产党领导的（    ）现代化，这是对中国式现代化的定性，是管总、管根本的。',options:['资本主义','社会主义','民主主义','科学主义'],answer:[1],explanation:'P44,47'},
{id:40,chapter:2,type:'multiple',question:'中国式现代化的中国特色包括（    ）。',options:['人口规模巨大的现代化','全体人民共同富裕的现代化','物质文明和精神文明相协调的现代化','人与自然和谐共生的现代化','走和平发展道路的现代化'],answer:[0,1,2,3,4],explanation:'P44-46'},
{id:41,chapter:2,type:'multiple',question:'推进中国式现代化需要牢牢把握的重大原则包括（    ）。',options:['坚持和加强党的全面领导','坚持中国特色社会主义道路','坚持以人民为中心的发展思想','坚持深化改革开放','坚持发扬斗争精神'],answer:[0,1,2,3,4],explanation:'P50-51'},
{id:42,chapter:2,type:'multiple',question:'中国式现代化（    ）。',options:['创造了人类文明新形态','提供了一种全新的现代化模式','是对西方式现代化理论和实践的重大超越','为广大发展中国家提供了全新选择'],answer:[0,1,2,3],explanation:'P48-49'},
{id:43,chapter:2,type:'multiple',question:'推进中国式现代化需要正确处理的重大关系包括（    ）。',options:['顶层设计与实践探索','战略与策略','守正与创新','效率与公平'],answer:[0,1,2,3],explanation:'P51'},
{id:44,chapter:2,type:'multiple',question:'全面建成小康社会（    ）。',options:['高质量完成了社会主义现代化建设"三步走"战略的第二步','使中华民族伟大复兴向前迈出新的一大步','探索了人类解决贫困问题的新路径','为推动人类文明进步作出了重大贡献'],answer:[0,1,2,3],explanation:'P39'},
{id:45,chapter:2,type:'multiple',question:'中国式现代化既基于自身国情、又借鉴各国经验，既（    ）。',options:['传承历史文化','融合现代文明','摒弃西方模式','照搬苏联经验'],answer:[0,1],explanation:'P41'},
{id:46,chapter:2,type:'fill',question:'中国式现代化是中国共产党领导的______现代化。',answer:'社会主义',explanation:'P44'},
{id:47,chapter:2,type:'fill',question:'党的二十大明确，全面建成社会主义现代化强国总的战略安排是分______走。',answer:'两',explanation:'P40'},
{id:48,chapter:2,type:'fill',question:'中国梦把国家的追求、民族的向往、人民的______融为一体。',answer:'期盼',explanation:'P37'},
{id:49,chapter:2,type:'fill',question:'中国式现代化作为科学社会主义的最新成果，坚持社会主义______和方向。',answer:'目标',explanation:'P49'},
{id:50,chapter:2,type:'fill',question:'中国式现代化打破了"______=西方化"的迷思。',answer:'现代化',explanation:'P48'},
{id:51,chapter:2,type:'fill',question:'团结奋斗是中国人民创造历史伟业的______。',answer:'必由之路',explanation:'P53'},
{id:52,chapter:3,type:'single',question:'中国特色社会主义最本质的特征是（    ）。',options:['人民当家作主','中国共产党领导','依法治国','社会主义制度'],answer:[1],explanation:'P56'},
{id:53,chapter:3,type:'single',question:'党的领导的最高原则是（    ）。',options:['坚持民主集中制','坚持党的全面领导','党中央集中统一领导','维护党中央权威'],answer:[2],explanation:'P66'},
{id:54,chapter:3,type:'single',question:'党的领导制度是我国的（    ）领导制度。',options:['基本','重要','根本','核心'],answer:[2],explanation:'P69'},
{id:55,chapter:3,type:'single',question:'中国特色社会主义制度体系中具有统领地位的是（    ）。',options:['根本制度','基本制度','重要制度','党的领导制度'],answer:[3],explanation:'P69'},
{id:56,chapter:3,type:'single',question:'（    ）是党的领导决策核心。',options:['全国人大、国务院、全国政协','中央委员会、中央政治局、中央政治局常委会','中央书记处、中央纪委、中央军委','省委、市委、县委'],answer:[1],explanation:'P71'},
{id:57,chapter:3,type:'single',question:'党的领导是全面的、系统的、整体的，并不是说（    ）。',options:['党组织发挥领导核心作用','党组织包揽包办一切','党组织领导一切工作','党组织协调各方'],answer:[1],explanation:'P66'},
{id:58,chapter:3,type:'single',question:'中国共产党自身优势是中国特色社会主义（    ）的主要来源。',options:['理论优势','制度优势','政治优势','组织优势'],answer:[1],explanation:'P59'},
{id:59,chapter:3,type:'single',question:'我国国家制度和国家治理体系具有多方面的显著优势，其中（    ）是带有统领性的根本优势。',options:['人民当家作主','中国共产党领导','依法治国','社会主义制度'],answer:[1],explanation:'P59'},
{id:60,chapter:3,type:'multiple',question:'为什么必须坚持党的全面领导？（    ）',options:['中国共产党的领导地位是在历史奋斗中形成的','中国共产党领导是人民当家作主的可靠保障','中国共产党领导关系中国特色社会主义的性质、方向和命运','中国共产党领导是实现中华民族伟大复兴的根本保证'],answer:[0,1,2,3],explanation:'P57-59'},
{id:61,chapter:3,type:'multiple',question:'中国共产党作为最高政治领导力量（    ）。',options:['不是自封的，而是在历史发展中形成的','是由我国国家性质和政治制度体系决定的','是由中华民族伟大复兴事业决定的','是自封的'],answer:[0,1,2],explanation:'P63-64'},
{id:62,chapter:3,type:'multiple',question:'党的领导是（    ）的。',options:['全面的','系统的','整体的','局部的'],answer:[0,1,2],explanation:'P65-66'},
{id:63,chapter:3,type:'multiple',question:'维护党中央权威和集中统一领导（    ）。',options:['是一个成熟的马克思主义执政党的重大建党原则','必须坚决贯彻党的理论、路线、方针政策和党中央的决策部署','最关键的是坚决维护习近平同志党中央的核心、全党的核心地位','同坚持党的民主集中制是完全一致的'],answer:[0,1,2,3],explanation:'P67-68'},
{id:64,chapter:3,type:'multiple',question:'坚持和加强党的全面领导（    ）。',options:['使党的领导核心作用充分彰显','使党的政治领导力、思想引领力、群众组织力、社会号召力显著增强','为推进新时代中国特色社会主义事业提供了政治保证','使党成为风雨来袭时中国人民最可靠的主心骨'],answer:[0,1,2,3],explanation:'P61-62'},
{id:65,chapter:3,type:'multiple',question:'党的领导制度（    ）。',options:['是我国的根本领导制度','是一个系统完备、内涵丰富的制度体系','明确了我国政治生活的领导关系、领导主体、领导对象','是中国特色社会主义制度体系的核心'],answer:[0,1,2,3],explanation:'P69-70'},
{id:66,chapter:3,type:'multiple',question:'加强党中央对重大工作的领导（    ）。',options:['是加强党的全面领导的制度安排','是实现党的全面领导的直接体现','是我们党的优良传统和宝贵经验','必须完善党中央重大决策部署落实机制'],answer:[0,1,2,3],explanation:'P70-71'},
{id:67,chapter:3,type:'multiple',question:'坚持和加强党的全面领导，必须健全党的全面领导制度：（    ）',options:['必须完善党在各种组织中发挥领导作用的制度','必须完善党协调各方的机制','必须完善党领导各项事业的具体制度','必须完善党管理一切事务的制度'],answer:[0,1,2],explanation:'P71-72'},
{id:68,chapter:3,type:'fill',question:'坚持党的全面领导是坚持和发展中国特色社会主义的______。',answer:'必由之路',explanation:'P56'},
{id:69,chapter:3,type:'fill',question:'中国最大的国情就是______的领导。',answer:'中国共产党',explanation:'P57'},
{id:70,chapter:3,type:'fill',question:'中国特色社会主义之所以是社会主义，究其根本就在于坚持科学社会主义基本原则，在于坚持______的领导。',answer:'中国共产党',explanation:'P58'},
{id:71,chapter:3,type:'fill',question:'中国特色社会主义制度的最大优势是______。',answer:'中国共产党领导',explanation:'P56'},
{id:72,chapter:3,type:'fill',question:'事在四方，要在______。党中央集中统一领导是党的领导的最高原则。',answer:'中央',explanation:'P66-67'},
{id:73,chapter:3,type:'fill',question:'党的领导是国家治理体系的______。',answer:'核心',explanation:'P69'},
{id:74,chapter:3,type:'fill',question:'党的领导制度是中国特色社会主义制度建设的______。',answer:'关键',explanation:'P69'},
{id:75,chapter:3,type:'fill',question:'坚持党中央集中统一领导是______政治原则。',answer:'最高',explanation:'P56'},
{id:76,chapter:4,type:'single',question:'马克思主义的本质属性和鲜明品格是（    ）。',options:['实践性','人民性','科学性','阶级性'],answer:[1],explanation:'P74'},
{id:77,chapter:4,type:'single',question:'我们党的最大政治优势是（    ）。',options:['理论联系实际','批评与自我批评','密切联系群众','民主集中制'],answer:[2],explanation:'P79'},
{id:78,chapter:4,type:'single',question:'人民立场是中国共产党的（    ）政治立场。',options:['根本','基本','重要','核心'],answer:[0],explanation:'P78'},
{id:79,chapter:4,type:'single',question:'（    ）是我们党的生命线和根本工作路线。',options:['实事求是','群众路线','独立自主','民主集中制'],answer:[1],explanation:'P84'},
{id:80,chapter:4,type:'single',question:'（    ）是获得真知灼见的源头活水，是贯彻群众路线的有效途径。',options:['理论学习','调查研究','实践锻炼','批评与自我批评'],answer:[1],explanation:'P85'},
{id:81,chapter:4,type:'multiple',question:'坚持人民立场，就要（    ）。',options:['始终牢记党的初心和使命','始终保持党同人民群众的血肉联系','热爱人民、尊重人民、敬畏人民','始终坚持以经济建设为中心'],answer:[0,1,2],explanation:'P78-79'},
{id:82,chapter:4,type:'multiple',question:'人民群众是（    ）。',options:['社会物质财富的创造者','社会精神财富的创造者','社会变革的决定力量','历史发展的旁观者'],answer:[0,1,2],explanation:'P75'},
{id:83,chapter:4,type:'multiple',question:'依靠人民创造历史伟业，必须（    ）。',options:['尊重人民主体地位','尊重人民首创精神','坚持党的领导','坚持依法治国'],answer:[0,1],explanation:'P81'},
{id:84,chapter:4,type:'multiple',question:'为人民造福，要（    ）。',options:['着力解决人民群众最关心最直接最现实的利益问题','一件事情接着一件事情办','一年接着一年干','一蹴而就'],answer:[0,1,2],explanation:'P86'},
{id:85,chapter:4,type:'multiple',question:'促进共同富裕，要把握好的原则包括（    ）。',options:['鼓励勤劳创新致富','坚持基本经济制度','尽力而为量力而行','坚持循序渐进'],answer:[0,1,2,3],explanation:'P88'},
{id:86,chapter:4,type:'fill',question:'江山就是______，人民就是江山。',answer:'人民',explanation:'P75'},
{id:87,chapter:4,type:'fill',question:'民心是最大的______，决定事业兴衰成败。',answer:'政治',explanation:'P76'},
{id:88,chapter:4,type:'fill',question:'时代是出卷人，我们是答卷人，______是阅卷人。',answer:'人民',explanation:'P82'},
{id:89,chapter:4,type:'fill',question:'共同富裕是中国特色社会主义的______要求，是中国式现代化的重要特征。',answer:'本质',explanation:'P87'},
{id:90,chapter:4,type:'fill',question:'人民是我们党的______、执政之基、力量之源。',answer:'生命之根',explanation:'P81'},
{id:91,chapter:5,type:'single',question:'改革开放是决定当代中国命运的（    ）。',options:['重要法宝','关键一招','根本保证','必由之路'],answer:[1],explanation:'P91'},
{id:92,chapter:5,type:'single',question:'改革发展稳定中，（    ）是解决一切经济社会问题的关键。',options:['改革','发展','稳定','开放'],answer:[1],explanation:'P103'},
{id:93,chapter:5,type:'single',question:'全面深化改革总目标是（    ）。',options:['完善中国特色社会主义制度','完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化','实现中华民族伟大复兴','建设社会主义现代化强国'],answer:[1],explanation:'P98'},
{id:94,chapter:5,type:'single',question:'全面深化改革以（    ）为重点。',options:['政治体制改革','经济体制改革','文化体制改革','社会体制改革'],answer:[1],explanation:'P99'},
{id:95,chapter:5,type:'multiple',question:'改革开放使中国创造了（    ）。',options:['经济快速发展奇迹','社会长期稳定奇迹','科技领先奇迹','文化繁荣奇迹'],answer:[0,1],explanation:'P92'},
{id:96,chapter:5,type:'multiple',question:'全面深化改革开放的正确方向包括（    ）。',options:['必须坚持和改善党的全面领导','必须坚持和完善中国特色社会主义制度','必须坚持以人民为中心','必须有利于进一步解放思想、解放和发展社会生产力、解放和增强社会活力'],answer:[0,1,2,3],explanation:'P96'},
{id:97,chapter:5,type:'multiple',question:'改革发展稳定是我国社会主义现代化建设的三个重要支点（    ）。',options:['改革是经济社会发展的强大动力','发展是解决一切经济社会问题的关键','稳定是改革发展的前提','开放是改革发展的基础'],answer:[0,1,2],explanation:'P103'},
{id:98,chapter:5,type:'multiple',question:'中国对外开放（    ）。',options:['不是要一家唱独角戏，而是要欢迎各方共同参与','不是要谋求势力范围，而是要支持各国共同发展','不是要营造自己的后花园，而是要建设各国共享的百花园','不是要关闭国门，而是要更大范围开放'],answer:[0,1,2],explanation:'P110'},
{id:99,chapter:5,type:'fill',question:'改革开放是坚持和发展中国特色社会主义的______。',answer:'必由之路',explanation:'P92'},
{id:100,chapter:5,type:'fill',question:'凡属重大改革要于法有据，需要修改法律的可以先修改法律，先______后破，有序进行。',answer:'立',explanation:'P104'},
{id:101,chapter:5,type:'fill',question:'国家治理体系和治理能力现代化，是一个国家______的重要标志。',answer:'现代化',explanation:'P100'},
{id:102,chapter:5,type:'fill',question:'稳定是改革发展的______。',answer:'前提',explanation:'P103'},
{id:103,chapter:6,type:'single',question:'高质量发展是全面建设社会主义现代化国家的（    ）。',options:['重要任务','首要任务','根本任务','基本任务'],answer:[1],explanation:'P112'},
{id:104,chapter:6,type:'single',question:'创新是引领发展的（    ）。',options:['重要动力','第一动力','核心动力','根本动力'],answer:[1],explanation:'P115'},
{id:105,chapter:6,type:'single',question:'共享是中国特色社会主义的（    ）。',options:['根本要求','本质要求','重要特征','基本原则'],answer:[1],explanation:'P115'},
{id:106,chapter:6,type:'single',question:'我国经济已由高速增长阶段转向（    ）发展阶段。',options:['中高速增长','高质量发展','效率优先','创新驱动'],answer:[1],explanation:'P113'},
{id:107,chapter:6,type:'single',question:'国有企业是中国特色社会主义的重要（    ）和政治基础。',options:['经济基础','物质基础','社会基础','理论基础'],answer:[1],explanation:'P121'},
{id:108,chapter:6,type:'single',question:'全面建设社会主义现代化国家，最艰巨最繁重的任务依然在（    ）。',options:['城市','农村','工业','服务业'],answer:[1],explanation:'P131'},
{id:109,chapter:6,type:'multiple',question:'新发展理念包括（    ）。',options:['创新','协调','绿色','开放','共享'],answer:[0,1,2,3,4],explanation:'P115'},
{id:110,chapter:6,type:'multiple',question:'高质量发展的战略意义包括（    ）。',options:['为全面建设社会主义现代化国家提供更为坚实的物质基础','是不断满足人民对美好生活需要的重要保证','是维护国家长治久安的必然要求','是实现共同富裕的唯一途径'],answer:[0,1,2],explanation:'P117'},
{id:111,chapter:6,type:'multiple',question:'社会主义基本经济制度包括（    ）。',options:['公有制为主体、多种所有制经济共同发展','按劳分配为主体、多种分配方式并存','社会主义市场经济体制','人民代表大会制度'],answer:[0,1,2],explanation:'P120'},
{id:112,chapter:6,type:'multiple',question:'构建新发展格局（    ）。',options:['是事关全局的系统性、深层次变革','是把握未来发展主动权的先手棋','是开放的国内国际双循环','是以全国统一大市场基础上的国内大循环为主体'],answer:[0,1,2,3],explanation:'P125'},
{id:113,chapter:6,type:'multiple',question:'公有制经济和非公有制经济（    ）。',options:['都是社会主义市场经济的重要组成部分','都是我国经济社会发展的重要基础','要毫不动摇巩固和发展公有制经济','要毫不动摇鼓励、支持、引导非公有制经济发展'],answer:[0,1,2,3],explanation:'P121'},
{id:114,chapter:6,type:'multiple',question:'实施乡村振兴战略，总要求包括（    ）。',options:['产业兴旺','生态宜居','乡风文明','治理有效、生活富裕'],answer:[0,1,2,3],explanation:'P131'},
{id:115,chapter:6,type:'fill',question:'新发展理念是实现高质量发展的______。',answer:'指导原则',explanation:'P113'},
{id:116,chapter:6,type:'fill',question:'协调是持续发展的______要求。',answer:'内在',explanation:'P115'},
{id:117,chapter:6,type:'fill',question:'绿色是永续发展的______条件。',answer:'必要',explanation:'P115'},
{id:118,chapter:6,type:'fill',question:'开放是国家繁荣发展的______。',answer:'必由之路',explanation:'P115'},
{id:119,chapter:6,type:'fill',question:'构建高水平社会主义市场经济体制，关键是要处理好______和市场的关系。',answer:'政府',explanation:'P124'},
{id:120,chapter:6,type:'fill',question:'建设现代化经济体系是我国发展的______。',answer:'战略目标',explanation:'P129'},
{id:121,chapter:7,type:'single',question:'教育、科技、人才是全面建设社会主义现代化国家的（    ）。',options:['重要支撑','基础性、战略性支撑','根本保障','关键力量'],answer:[1],explanation:'P135'},
{id:122,chapter:7,type:'single',question:'科技自立自强是国家强盛之（    ）、安全之（    ）。',options:['基；要','本；基','要；基','基；要'],answer:[3],explanation:'P146'},
{id:123,chapter:7,type:'single',question:'基础研究是科技创新的（    ）。',options:['根本','源头','关键','核心'],answer:[1],explanation:'P150'},
{id:124,chapter:7,type:'single',question:'培养什么人、怎样培养人、为谁培养人是教育的（    ），也是建设教育强国的核心课题。',options:['基本任务','根本问题','重要目标','核心内容'],answer:[1],explanation:'P142'},
{id:125,chapter:7,type:'multiple',question:'实施创新驱动发展战略，要坚持面向（    ）。',options:['世界科技前沿','经济主战场','国家重大需求','人民生命健康'],answer:[0,1,2,3],explanation:'P139'},
{id:126,chapter:7,type:'multiple',question:'建设教育强国是（    ）。',options:['全面建成社会主义现代化强国的战略先导','实现高水平科技自立自强的重要支撑','促进全体人民共同富裕的有效途径','以中国式现代化全面推进中华民族伟大复兴的基础工程'],answer:[0,1,2,3],explanation:'P140'},
{id:127,chapter:7,type:'multiple',question:'必须坚持（    ），加快教育强国、科技强国、人才强国建设。',options:['科技是第一生产力','人才是第一资源','创新是第一动力','教育是第一基础'],answer:[0,1,2],explanation:'P135'},
{id:128,chapter:7,type:'multiple',question:'坚持党对人才工作的全面领导是做好人才工作的（    ）。',options:['根本保证','重要保障','社会条件','基本前提'],answer:[0],explanation:'P154'},
{id:129,chapter:7,type:'fill',question:'全面建设社会主义现代化国家，教育是______，科技是关键，人才是基础。',answer:'根本',explanation:'P135'},
{id:130,chapter:7,type:'fill',question:'科教兴国是我国的______。',answer:'基本国策',explanation:'P138'},
{id:131,chapter:7,type:'fill',question:'育人的根本在于______。',answer:'立德',explanation:'P142'},
{id:132,chapter:7,type:'fill',question:'人才是实现民族振兴、赢得国际竞争主动的______资源。',answer:'战略',explanation:'P151'}];"""

new_content = content[:start] + new_questions + content[end:]
with open('习思想期末复习/刷题题库.html', 'w', encoding='utf-8') as f:
    f.write(new_content)
print('OK')
